### ISSUE TITLE
Ruby 2.2 Support?

### ISSUE THREAD

**Issue by samnang** [tmm1/gctools#11]
After I upgraded my Rails(4.1.8) to Ruby 2.2.0. I notice some error messages in my logs:

```
app web.1     - - E, [2015-01-02T04:19:12.265987 #12] ERROR -- : listen loop error: unknown key: old_object (ArgumentError)
app web.1     - - E, [2015-01-02T04:19:12.266103 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/gctools-0.2.3/lib/gctools/oobgc/unicorn_middleware.rb:14:in `run'
app web.1     - - E, [2015-01-02T04:19:12.266146 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/gctools-0.2.3/lib/gctools/oobgc/unicorn_middleware.rb:14:in `process_client'
app web.1     - - E, [2015-01-02T04:19:12.266177 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-worker-killer-0.4.2/lib/unicorn/worker_killer.rb:51:in `process_client'
app web.1     - - E, [2015-01-02T04:19:12.266207 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-worker-killer-0.4.2/lib/unicorn/worker_killer.rb:124:in `process_client'
app web.1     - - E, [2015-01-02T04:19:12.266237 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
app web.1     - - E, [2015-01-02T04:19:12.266267 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
app web.1     - - E, [2015-01-02T04:19:12.266296 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
app web.1     - - E, [2015-01-02T04:19:12.266324 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
app web.1     - - E, [2015-01-02T04:19:12.266354 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
app web.1     - - E, [2015-01-02T04:19:12.266381 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

I was wondering do we still suppose to use it on Ruby 2.2? Or it should only be used on Ruby 2.1?

**Comment by tmm1** [comment]
oobgc is unnecessary in Ruby 2.2, since it includes an incremental GC (RIncGC) and will not pause the world for a long time.

**Comment by samnang** [comment]
Thank @tmm1 .

**Comment by tmm1** [comment]
I'm going to leave this open (so others can find it) until I get a chance to update the README.

**Comment by noach-cellogicmobile** [comment]
Any chance you might merge hale's pull request?   I, too, inferred that gctools was still relevant to Ruby >= 2.2, since the repo had recent commits but had no mention of being obsolete.  Thanks!

**Comment by jdowning** [comment]
@tmm1 I believe `v0.2.4` supports ruby >= 2.2 quite well [now](https://github.com/tmm1/gctools/compare/01b8379682547a56098462c6e930a456a38b4288...db39dac947e1185de7448a2706fe0f305b24f48f).

**Comment by thedrow** [comment]
So if it's not needed in 2.2 what does it do when we run it in Ruby 2.2?

**Comment by jdowning** [comment]
@thedrow I believe it "just works". I think [this commit](https://github.com/tmm1/gctools/commit/8ecfd3fb803165c3ac4160fb1229d345e2e8b4e4) adds support for the ruby 2.2 symbol name.

I'm using it with Rails 4 + Ruby 2.3 just fine.

**Comment by thedrow** [comment]
I'm confused. It doesn't fail but it does nothing useful on 2.2? Or does it still provide a benefit when running under MRI Ruby 2.2?

**Comment by peteygao** [comment]
The answer to "is there a benefit" is... wait for it... workload dependent. Tada! What a shocker!

RIncGC behaves differently from a web-request-based "Out-of-band GC", so you can't replace one with the other and expect the exact same performance behaviour.

If your app spawns a lot of temp vars and triggers multiple GC runs during every request, and you'd like to have a clean slate before every new request (and avoid triggering as many GC _during_ requests--remember, RIncGC still slows your app down, they just won't block for the entire duration of a GC run), then OOBGC can still be helpful. If, on the other hand, you've kept your app pretty light and there isn't a lot of garbage created per request, and a GC is only triggered once every few requests, then OOBGC will actually hurt you (very slightly) than give any benefits.

However, these are broad stroke assumptions! You MUST profile your specific app!

Where assumption and reality diverge is where you'll have performance issues.
