### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by dblock** [tmm1/gctools#15]
Noticed 

```
/app/vendor/bundle/ruby/2.2.0/gems/gctools-0.2.3/lib/gctools/oobgc/unicorn_middleware.rb:14: warning: GC.stat keys were changed from Ruby 2.1. In this case, you refer to obsolete `total_allocated_object' (new key is `total_allocated_objects'). Please check <https://bugs.ruby-lang.org/issues/9924> for more information.
```

Looks already fixed on HEAD in https://github.com/tmm1/gctools/pull/14, maybe cut a release?

**Comment by tmm1** [comment]
Done.

**Comment by dblock** [comment]
:+1:

**Comment by dblock** [comment]
0.2.4 now creates some new type of havoc

```
E, [2016-02-11T00:17:25.726046 #159] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
E, [2016-02-11T00:17:25.726078 #159] ERROR -- : config.ru:20:in `block (2 levels) in <main>'
E, [2016-02-11T00:17:25.721293 #159] ERROR -- : St Pats Students' Union: invalid distance too far back, restarting in 1 second(s).
E, [2016-02-11T00:17:25.724724 #159] ERROR -- : eBay Classifieds Group: buffer error, restarting in 1 second(s).
E, [2016-02-11T00:17:26.745753 #159] ERROR -- : listen loop error: undefined method `<<' for nil:NilClass (NoMethodError)
E, [2016-02-11T00:17:26.746210 #159] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1068:in `block in spawn_threadpool'
E, [2016-02-11T00:17:27.745368 #159] ERROR -- : listen loop error: undefined method `<<' for nil:NilClass (NoMethodError)
E, [2016-02-11T00:17:27.746111 #159] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1068:in `block in spawn_threadpool'
I, [2016-02-11T00:17:46.873878 #22]  INFO -- : reaped #<Process::Status: pid 159 exit 0> worker=0
```

Haven't debugged yet.
